package hohserg.advancedauromancy.items

import hohserg.advancedauromancy.client.render.simpleItem.SimpleTexturedModelProvider
import hohserg.advancedauromancy.items.base.ItemSelfRegister

class ItemUpgrade(val name:String) extends ItemSelfRegister with SimpleTexturedModelProvider